# Generated by Django 5.0.1 on 2024-01-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('foto', models.ImageField(upload_to='images/')),
                ('text', models.TextField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
